### ISSUE TITLE
This value is not stored, then why is this calculated?

### ISSUE THREAD

**Issue by itsmohitanand** [strumke/hsic_python#2]
https://github.com/strumke/hsic_python/blob/45aa892d518eaefb4b0e1fffb92a2bb728f1fe15/hsic.py#L45

**Comment by strumke** [comment]
> https://github.com/strumke/hsic_python/blob/45aa892d518eaefb4b0e1fffb92a2bb728f1fe15/hsic.py#L45

Hi,
thanks for noticing this, and you're right. I'm not sure if the function should instead have returned this value, and I don't have time to investigate right now. Since this function is a Gaussian, it's not entirely unlikely that the exponential should be returned.

**Comment by itsmohitanand** [comment]
@strumke My bad, I looked through np.exp(), it takes an input argument and also takes an out argument where the result should be stored. This equation is same as KX = np.exp(KX), hence I think the code is correct.
